"""CLI entry point for the SQLPrism MCP server.

Reads config from a YAML or JSON file (or command-line arguments),
initialises the server, and runs it.
"""

import json
import logging
import sys
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import TYPE_CHECKING

import click
import yaml

from sqlprism.core.mcp_tools import configure, mcp
from sqlprism.types import parse_repo_config

if TYPE_CHECKING:
    from sqlprism.core.graph import GraphDB
    from sqlprism.core.indexer import Indexer

DEFAULT_DB_PATH = Path.home() / ".sqlprism" / "graph.duckdb"
LEGACY_CONFIG_PATH = Path.home() / ".sqlprism" / "config.json"

# Discovery order for config files in the working directory
_CONFIG_NAMES = ("sqlprism.yml", "sqlprism.yaml", "sqlprism.json")


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(path: str | None = None) -> dict:
    """Load config from YAML or JSON file with automatic discovery.

    Discovery order when *path* is ``None``:

    1. ``sqlprism.yml`` in the working directory
    2. ``sqlprism.yaml`` in the working directory
    3. ``sqlprism.json`` in the working directory
    4. ``~/.sqlprism/config.json`` (legacy location)

    Args:
        path: Explicit config file path.  When provided, only that
            file is tried (no discovery).

    Returns:
        Parsed config dict.

    Raises:
        FileNotFoundError: No config file found in any location.
    """
    if path is not None:
        resolved = Path(path)
        if not resolved.exists():
            raise FileNotFoundError(
                f"Config file not found: {resolved}\n"
                "Create one with: sqlprism init"
            )
        return _parse_config_file(resolved)

    cwd = Path.cwd()
    for name in _CONFIG_NAMES:
        candidate = cwd / name
        if candidate.exists():
            return _parse_config_file(candidate)

    if LEGACY_CONFIG_PATH.exists():
        return _parse_config_file(LEGACY_CONFIG_PATH)

    raise FileNotFoundError(
        "No config file found. Searched:\n"
        + "".join(f"  - {cwd / n}\n" for n in _CONFIG_NAMES)
        + f"  - {LEGACY_CONFIG_PATH}\n"
        + "Create one with: sqlprism init"
    )


def _parse_config_file(path: Path) -> dict:
    """Parse a YAML or JSON config file."""
    suffix = path.suffix.lower()
    if suffix not in (".yml", ".yaml", ".json"):
        raise click.ClickException(
            f"Unsupported config format: {path.suffix}. Use .yml, .yaml, or .json"
        )
    try:
        text = path.read_text()
        if suffix in (".yml", ".yaml"):
            result = yaml.safe_load(text) or {}
        else:
            result = json.loads(text) if text.strip() else {}
    except (yaml.YAMLError, json.JSONDecodeError, OSError) as e:
        raise click.ClickException(f"Failed to parse {path}: {e}") from e
    if not isinstance(result, dict):
        raise click.ClickException(
            f"Config must be a mapping, got {type(result).__name__} in {path}"
        )
    return result


def _try_load_config(path: str | None) -> dict:
    """Try to load config, return empty dict if not found.

    Unlike ``_cli_load_config``, does not raise on missing config.
    Used by commands that work with just ``--db`` and no config.
    """
    try:
        return load_config(path)
    except FileNotFoundError:
        return {}


def _cli_load_config(path: str | None) -> dict:
    """CLI wrapper: converts FileNotFoundError to a friendly click error."""
    try:
        return load_config(path)
    except FileNotFoundError as e:
        raise click.ClickException(str(e)) from e


# ---------------------------------------------------------------------------
# Repo-config merging
# ---------------------------------------------------------------------------

# (config_key, repo_type, path_key). path_key is None for "sql" because those
# configs already carry a "path" field directly; for dbt/sqlmesh the path is
# mirrored from "project_path".
_REPO_TYPE_SPECS: tuple[tuple[str, str, str | None], ...] = (
    ("repos", "sql", None),
    ("dbt_repos", "dbt", "project_path"),
    ("sqlmesh_repos", "sqlmesh", "project_path"),
)


def _build_repo_configs(config: dict) -> dict:
    """Merge repos, dbt_repos, sqlmesh_repos into a single dict with repo_type tags.

    Preserves full config for dbt/sqlmesh so reindex_files() can access
    renderer params (profiles_dir, env_file, target, variables, etc.).

    Entries whose name starts with ``#`` are treated as YAML-template comments
    and skipped — these come from the default config generated by
    ``sqlprism init`` and are never meant to be indexed.
    """
    result: dict[str, dict] = {}
    for config_key, repo_type, path_key in _REPO_TYPE_SPECS:
        for name, cfg in config.get(config_key, {}).items():
            if name.startswith("#"):
                continue
            if isinstance(cfg, dict):
                entry = {**cfg, "repo_type": repo_type}
                if path_key is not None:
                    entry["path"] = cfg[path_key]
                result[name] = entry
            elif path_key is None:
                # Short form is only supported for SQL: {name: "/path/to/repo"}.
                result[name] = {"path": cfg, "repo_type": repo_type}
            else:
                raise click.ClickException(
                    f"{repo_type} repo '{name}' must be a mapping with "
                    f"'{path_key}', got {type(cfg).__name__}"
                )
    return result


# ---------------------------------------------------------------------------
# GraphDB open helpers
# ---------------------------------------------------------------------------

@contextmanager
def _open_graph_for_write(
    config_path: str | None,
    db_path: str | None,
) -> Iterator[tuple["GraphDB", dict, str]]:
    """Load config, ensure DB parent dir exists, open GraphDB for a write command.

    Yields ``(graph, config, effective_db_path)`` and closes the graph on exit.
    """
    from sqlprism.core.graph import GraphDB

    config = _cli_load_config(config_path)
    effective_db_path = db_path or config.get("db_path", str(DEFAULT_DB_PATH))
    Path(effective_db_path).parent.mkdir(parents=True, exist_ok=True)
    with GraphDB(effective_db_path) as graph:
        yield graph, config, effective_db_path


@contextmanager
def _open_graph_for_read(
    config_path: str | None,
    db_path: str | None,
    *,
    require_config: bool = True,
    missing_on_stderr: bool = True,
) -> Iterator[tuple["GraphDB", dict, str]]:
    """Load config, verify DB exists, open GraphDB for a read-only command.

    Yields ``(graph, config, effective_db_path)`` and closes the graph on exit.
    Exits with code 1 when the DB does not exist.

    ``require_config=False`` tolerates a missing config file (for commands
    that can run with just ``--db``). ``missing_on_stderr=False`` preserves
    legacy commands that wrote the "No index found" message to stdout.
    """
    from sqlprism.core.graph import GraphDB

    loader = _cli_load_config if require_config else _try_load_config
    config = loader(config_path)
    effective_db_path = db_path or config.get("db_path", str(DEFAULT_DB_PATH))
    if not Path(effective_db_path).exists():
        click.echo(
            "No index found. Run 'sqlprism reindex' first.",
            err=missing_on_stderr,
        )
        sys.exit(1)
    with GraphDB(effective_db_path) as graph:
        yield graph, config, effective_db_path


# ---------------------------------------------------------------------------
# Per-repo-type reindex handlers
# ---------------------------------------------------------------------------

def _reindex_sql_repo(
    indexer: "Indexer", name: str, cfg: dict, sql_dialect: str | None,
) -> list[str]:
    path, dialect, dialect_overrides = parse_repo_config(cfg, sql_dialect)
    click.echo(f"Indexing {name} ({path}){f' [{dialect}]' if dialect else ''}...")
    stats = indexer.reindex_repo(
        name,
        path,
        dialect=dialect,
        dialect_overrides=dialect_overrides,
    )
    click.echo(
        f"  scanned={stats['files_scanned']}, "
        f"added={stats['files_added']}, "
        f"changed={stats['files_changed']}, "
        f"removed={stats['files_removed']}, "
        f"nodes={stats['nodes_added']}, "
        f"edges={stats['edges_added']}, "
        f"column_usage={stats['column_usage_added']}"
    )
    return stats.get("parse_errors") or []


def _reindex_sqlmesh_repo(
    indexer: "Indexer", name: str, cfg: dict, _sql_dialect: str | None,
) -> list[str]:
    click.echo(f"Indexing sqlmesh project {name} ({cfg['project_path']})...")
    variables: dict[str, str | int] = cfg.get("variables", {})
    stats = indexer.reindex_sqlmesh(
        repo_name=name,
        project_path=cfg["project_path"],
        env_file=cfg.get("env_file"),
        variables=variables,
        dialect=cfg.get("dialect", "athena"),
        sqlmesh_command=cfg.get("sqlmesh_command", "uv run python"),
    )
    click.echo(
        f"  models={stats['models_rendered']}, "
        f"nodes={stats['nodes_added']}, "
        f"edges={stats['edges_added']}, "
        f"column_usage={stats['column_usage_added']}"
    )
    return []


def _reindex_dbt_repo(
    indexer: "Indexer", name: str, cfg: dict, _sql_dialect: str | None,
) -> list[str]:
    click.echo(f"Indexing dbt project {name} ({cfg['project_path']})...")
    stats = indexer.reindex_dbt(
        repo_name=name,
        project_path=cfg["project_path"],
        profiles_dir=cfg.get("profiles_dir"),
        env_file=cfg.get("env_file"),
        target=cfg.get("target"),
        dbt_command=cfg.get("dbt_command", "uv run dbt"),
        dialect=cfg.get("dialect"),
    )
    click.echo(
        f"  models={stats['models_compiled']}, "
        f"nodes={stats['nodes_added']}, "
        f"edges={stats['edges_added']}, "
        f"column_usage={stats['column_usage_added']}"
    )
    return []


_REINDEX_HANDLERS: dict[
    str,
    Callable[["Indexer", str, dict, str | None], list[str]],
] = {
    "sql": _reindex_sql_repo,
    "sqlmesh": _reindex_sqlmesh_repo,
    "dbt": _reindex_dbt_repo,
}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

@click.group()
@click.option(
    "--log-level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"], case_sensitive=False),
    default="WARNING",
    help="Set logging verbosity",
)
@click.pass_context
def cli(ctx, log_level):
    """SQLPrism — SQL knowledge graph for your codebase."""
    ctx.ensure_object(dict)
    logging.basicConfig(
        level=getattr(logging, log_level.upper()),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
    )


@cli.command()
@click.option(
    "--config",
    "config_path",
    type=click.Path(),
    default=None,
    help="Path to config file",
)
@click.option(
    "--db",
    "db_path",
    type=click.Path(),
    default=None,
    help="Path to DuckDB file (overrides config)",
)
@click.option(
    "--transport",
    type=click.Choice(["stdio", "streamable-http"]),
    default="stdio",
    help="MCP transport mode",
)
@click.option("--port", type=int, default=8000, help="Port for HTTP transport")
def serve(config_path: str, db_path: str | None, transport: str, port: int):
    """Start the MCP server."""
    # Servers need more visibility — override to INFO unless already more verbose
    root_logger = logging.getLogger()
    if root_logger.level > logging.INFO:
        logging.basicConfig(
            level=logging.INFO,
            force=True,
            format="%(asctime)s %(levelname)s %(name)s: %(message)s",
            datefmt="%Y-%m-%dT%H:%M:%S",
        )
    config = _cli_load_config(config_path)

    effective_db_path = db_path or config.get("db_path", str(DEFAULT_DB_PATH))

    Path(effective_db_path).parent.mkdir(parents=True, exist_ok=True)

    all_repos = _build_repo_configs(config)

    configure(
        db_path=effective_db_path,
        repos=all_repos,
        sql_dialect=config.get("sql_dialect"),
    )

    if transport == "stdio":
        mcp.run()
    else:
        mcp.settings.port = port
        mcp.run(transport="streamable-http")


@cli.command()
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--repo", "repo_name", type=str, default=None, help="Reindex a specific repo only")
def reindex(config_path: str, db_path: str | None, repo_name: str | None):
    """Run a manual reindex from the command line."""
    from sqlprism.core.indexer import Indexer

    all_parse_errors: list[str] = []

    with _open_graph_for_write(config_path, db_path) as (graph, config, _):
        indexer = Indexer(graph)
        all_repos = _build_repo_configs(config)

        if repo_name:
            if repo_name not in all_repos:
                click.echo(f"Error: repo '{repo_name}' not in config", err=True)
                sys.exit(1)
            all_repos = {repo_name: all_repos[repo_name]}

        sql_dialect = config.get("sql_dialect")
        for name, cfg in all_repos.items():
            handler = _REINDEX_HANDLERS[cfg["repo_type"]]
            all_parse_errors.extend(handler(indexer, name, cfg, sql_dialect))

    if all_parse_errors:
        click.echo(f"\n{len(all_parse_errors)} parse error(s):", err=True)
        for err in all_parse_errors:
            click.echo(f"  {err}", err=True)
        sys.exit(1)

    click.echo("Done.")


@cli.command("reindex-file")
@click.argument("paths", nargs=-1, required=True, type=click.Path())
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
def reindex_file(paths, config_path, db_path):
    """Reindex specific files (fast on-save path).

    Accepts one or more file paths. Resolves each to its repo,
    determines repo type, and reindexes only the affected models.
    Deleted file paths trigger removal of stale nodes from the graph.

    For editors without MCP integration:
      vim: autocmd BufWritePost *.sql silent !sqlprism reindex-file %:p
    """
    from sqlprism.core.indexer import Indexer

    with _open_graph_for_write(config_path, db_path) as (graph, config, _):
        repo_configs = _build_repo_configs(config)
        indexer = Indexer(graph)

        # Register repos so reindex_files can resolve paths
        for name, cfg in repo_configs.items():
            graph.upsert_repo(name, cfg["path"], repo_type=cfg["repo_type"])

        resolved_paths: list[str | Path] = [str(Path(p).resolve()) for p in paths]
        stats = indexer.reindex_files(paths=resolved_paths, repo_configs=repo_configs)

    click.echo(
        f"reindexed={stats['reindexed']}, "
        f"skipped={stats['skipped']}, "
        f"deleted={stats['deleted']}"
    )
    if stats["errors"]:
        click.echo(f"{len(stats['errors'])} error(s):", err=True)
        for err in stats["errors"]:
            click.echo(f"  {err}", err=True)
        sys.exit(1)


@cli.command("reindex-sqlmesh")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--name", "repo_name", type=str, required=True, help="Repo name for the index")
@click.option(
    "--project",
    "project_path",
    type=click.Path(exists=True),
    required=True,
    help="Path to sqlmesh project dir (containing config.yaml)",
)
@click.option(
    "--env-file",
    type=click.Path(exists=True),
    default=None,
    help="Path to .env file for sqlmesh config",
)
@click.option("--dialect", type=str, default="athena", help="SQL dialect (default: athena)")
@click.option(
    "--var",
    "variables",
    type=(str, str),
    multiple=True,
    help="SQLMesh variables as key value pairs, e.g. --var GRACE_PERIOD 7",
)
@click.option(
    "--sqlmesh-command",
    type=str,
    default="uv run python",
    help="Command to run python in sqlmesh venv (default: 'uv run python')",
)
def reindex_sqlmesh(
    config_path: str,
    db_path: str | None,
    repo_name: str,
    project_path: str,
    env_file: str | None,
    dialect: str,
    variables: tuple[tuple[str, str], ...],
    sqlmesh_command: str,
):
    """Index a sqlmesh project by rendering all models."""
    from sqlprism.core.indexer import Indexer

    var_dict: dict[str, str | int] = {}
    for k, v in variables:
        try:
            var_dict[k] = int(v)
        except ValueError:
            var_dict[k] = v

    with _open_graph_for_write(config_path, db_path) as (graph, _, _):
        indexer = Indexer(graph)
        click.echo(f"Rendering sqlmesh models from {project_path}...")
        stats = indexer.reindex_sqlmesh(
            repo_name=repo_name,
            project_path=project_path,
            env_file=env_file,
            variables=var_dict,
            dialect=dialect,
            sqlmesh_command=sqlmesh_command,
        )
        skipped = stats.get('models_skipped', 0)
        removed = stats.get('models_removed', 0)
        cached = stats.get('render_cached', False)
        skip_info = f", skipped={skipped}" if skipped else ""
        remove_info = f", removed={removed}" if removed else ""
        cache_info = " (render cached)" if cached else ""
        click.echo(
            f"  models={stats['models_rendered']}{skip_info}{remove_info}{cache_info}, "
            f"nodes={stats['nodes_added']}, "
            f"edges={stats['edges_added']}, "
            f"column_usage={stats['column_usage_added']}"
        )

    click.echo("Done.")


@cli.command("reindex-dbt")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--name", "repo_name", type=str, required=True, help="Repo name for the index")
@click.option(
    "--project",
    "project_path",
    type=click.Path(exists=True),
    required=True,
    help="Path to dbt project dir (containing dbt_project.yml)",
)
@click.option(
    "--profiles-dir",
    type=click.Path(exists=True),
    default=None,
    help="Path to directory containing profiles.yml (defaults to project dir)",
)
@click.option(
    "--env-file",
    type=click.Path(exists=True),
    default=None,
    help="Path to .env file for dbt connection variables",
)
@click.option("--target", type=str, default=None, help="dbt target name")
@click.option(
    "--dbt-command",
    type=str,
    default="uv run dbt",
    help="Command to invoke dbt (default: 'uv run dbt')",
)
@click.option(
    "--dialect",
    type=str,
    default=None,
    help="SQL dialect for parsing (e.g. starrocks, mysql, postgres)",
)
def reindex_dbt_cmd(
    config_path: str,
    db_path: str | None,
    repo_name: str,
    project_path: str,
    profiles_dir: str | None,
    env_file: str | None,
    target: str | None,
    dbt_command: str,
    dialect: str | None,
):
    """Index a dbt project by compiling all models."""
    from sqlprism.core.indexer import Indexer

    with _open_graph_for_write(config_path, db_path) as (graph, _, _):
        indexer = Indexer(graph)
        click.echo(f"Compiling dbt models from {project_path}...")
        stats = indexer.reindex_dbt(
            repo_name=repo_name,
            project_path=project_path,
            profiles_dir=profiles_dir,
            env_file=env_file,
            target=target,
            dbt_command=dbt_command,
            dialect=dialect,
        )
        click.echo(
            f"  models={stats['models_compiled']}, "
            f"nodes={stats['nodes_added']}, "
            f"edges={stats['edges_added']}, "
            f"column_usage={stats['column_usage_added']}"
        )

    click.echo("Done.")


@cli.group()
def query():
    """Query the knowledge graph."""
    pass


@query.command("search")
@click.argument("pattern")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--kind", type=str, default=None, help="Filter by node kind")
@click.option("--schema", type=str, default=None, help="Filter by schema")
@click.option("--repo", type=str, default=None, help="Filter by repo name")
@click.option("--limit", type=int, default=20, help="Max results (default 20)")
def query_search(
    config_path: str,
    db_path: str | None,
    pattern: str,
    kind: str | None,
    schema: str | None,
    repo: str | None,
    limit: int,
):
    """Search nodes by name pattern."""
    with _open_graph_for_read(config_path, db_path) as (graph, _, _):
        result = graph.query_search(
            pattern=pattern,
            kind=kind,
            schema=schema,
            repo=repo,
            limit=limit,
            include_snippets=False,
        )
    click.echo(json.dumps(result, indent=2, default=str))


@query.command("references")
@click.argument("name")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--kind", type=str, default=None, help="Filter by node kind")
@click.option("--schema", type=str, default=None, help="Filter by schema")
@click.option("--repo", type=str, default=None, help="Filter by repo name")
@click.option(
    "--direction",
    type=click.Choice(["both", "inbound", "outbound"]),
    default="both",
    help="Edge direction (default both)",
)
def query_references(
    config_path: str,
    db_path: str | None,
    name: str,
    kind: str | None,
    schema: str | None,
    repo: str | None,
    direction: str,
):
    """Find all references to/from a named entity."""
    with _open_graph_for_read(config_path, db_path) as (graph, _, _):
        result = graph.query_references(
            name=name,
            kind=kind,
            schema=schema,
            repo=repo,
            direction=direction,
            include_snippets=False,
        )
    click.echo(json.dumps(result, indent=2, default=str))


@query.command("column-usage")
@click.argument("table")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--column", type=str, default=None, help="Filter by column name")
@click.option("--usage-type", type=str, default=None, help="Filter by usage type")
@click.option("--repo", type=str, default=None, help="Filter by repo name")
def query_column_usage(
    config_path: str,
    db_path: str | None,
    table: str,
    column: str | None,
    usage_type: str | None,
    repo: str | None,
):
    """Find column usage for a table."""
    with _open_graph_for_read(config_path, db_path) as (graph, _, _):
        result = graph.query_column_usage(
            table=table,
            column=column,
            usage_type=usage_type,
            repo=repo,
        )
    click.echo(json.dumps(result, indent=2, default=str))


@query.command("trace")
@click.argument("name")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--kind", type=str, default=None, help="Filter by node kind")
@click.option(
    "--direction",
    type=click.Choice(["downstream", "upstream", "both"]),
    default="downstream",
    help="Trace direction (default downstream)",
)
@click.option("--max-depth", type=int, default=3, help="Max traversal depth (default 3)")
@click.option("--repo", type=str, default=None, help="Filter by repo name")
def query_trace(
    config_path: str,
    db_path: str | None,
    name: str,
    kind: str | None,
    direction: str,
    max_depth: int,
    repo: str | None,
):
    """Trace multi-hop dependency chains from a named entity."""
    with _open_graph_for_read(config_path, db_path) as (graph, _, _):
        result = graph.query_trace(
            name=name,
            kind=kind,
            direction=direction,
            max_depth=max_depth,
            repo=repo,
            include_snippets=False,
        )
    click.echo(json.dumps(result, indent=2, default=str))


@query.command("lineage")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--table", type=str, default=None, help="Filter by hop table name")
@click.option("--column", type=str, default=None, help="Filter by column name")
@click.option("--output-node", type=str, default=None, help="Filter by output node name")
@click.option("--repo", type=str, default=None, help="Filter by repo name")
def query_lineage(
    config_path: str,
    db_path: str | None,
    table: str | None,
    column: str | None,
    output_node: str | None,
    repo: str | None,
):
    """Query column lineage chains."""
    with _open_graph_for_read(config_path, db_path) as (graph, _, _):
        result = graph.query_column_lineage(
            table=table,
            column=column,
            output_node=output_node,
            repo=repo,
        )
    click.echo(json.dumps(result, indent=2, default=str))


@cli.command()
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
def status(config_path: str, db_path: str | None):
    """Show current index status."""
    with _open_graph_for_read(config_path, db_path, missing_on_stderr=False) as (graph, _, _):
        info = graph.get_index_status()
    click.echo(json.dumps(info, indent=2, default=str))


@cli.group()
def conventions():
    """Manage convention inference and overrides."""
    pass


@conventions.command("init")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option("--force", is_flag=True, help="Overwrite existing conventions file")
def conventions_init(config_path: str, db_path: str | None, force: bool):
    """Generate a sqlprism.conventions.yml with inferred conventions.

    Runs inference and writes a YAML file with confidence scores as comments.
    Review and adjust the file, then re-run reindex to apply overrides.
    """
    from sqlprism.core.conventions import ConventionEngine

    with _open_graph_for_read(
        config_path,
        db_path,
        require_config=False,
        missing_on_stderr=False,
    ) as (graph, _, _):
        output_path = Path("sqlprism.conventions.yml")
        if output_path.exists() and not force:
            click.echo(
                f"{output_path} already exists. Use --force to overwrite."
            )
            sys.exit(1)

        repos = graph._execute_read("SELECT repo_id FROM repos").fetchall()
        if not repos:
            click.echo("No repos indexed. Run 'sqlprism reindex' first.")
            sys.exit(1)

        repo_id = repos[0][0]
        if len(repos) > 1:
            click.echo(
                f"Warning: {len(repos)} repos found; using first repo. "
                "Use 'conventions refresh' to process all repos.",
                err=True,
            )
        engine = ConventionEngine(graph, repo_id)
        engine.run_inference()

        yaml_content = engine.generate_yaml()
        output_path.write_text(yaml_content)
        click.echo(f"Wrote {output_path}")


@conventions.command("refresh")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
def conventions_refresh(config_path: str, db_path: str | None):
    """Re-run convention inference without writing YAML.

    Updates the conventions and semantic_tags tables in the database.
    Useful after reindex to see how conventions changed.
    """
    from sqlprism.core.conventions import ConventionEngine

    with _open_graph_for_read(
        config_path,
        db_path,
        require_config=False,
        missing_on_stderr=False,
    ) as (graph, _, _):
        repos = graph._execute_read("SELECT repo_id FROM repos").fetchall()
        if not repos:
            click.echo("No repos indexed.")
            sys.exit(1)

        for (repo_id,) in repos:
            engine = ConventionEngine(graph, repo_id)
            result = engine.run_inference()
            click.echo(
                f"Repo {repo_id}: {result['layers_detected']} layers, "
                f"{result['conventions_stored']} conventions stored"
            )

    click.echo("Done.")


@conventions.command("diff")
@click.option("--config", "config_path", type=click.Path(), default=None)
@click.option("--db", "db_path", type=click.Path(), default=None)
@click.option(
    "--file",
    "yaml_file",
    type=click.Path(),
    default="sqlprism.conventions.yml",
    help="Conventions YAML file to compare against",
)
def conventions_diff(config_path: str, db_path: str | None, yaml_file: str):
    """Show what changed since last --init.

    Compares current conventions in the database against the YAML file.
    """
    from sqlprism.core.conventions import ConventionEngine

    with _open_graph_for_read(
        config_path,
        db_path,
        require_config=False,
        missing_on_stderr=False,
    ) as (graph, _, _):
        repos = graph._execute_read("SELECT repo_id FROM repos").fetchall()
        if not repos:
            click.echo("No repos indexed.")
            sys.exit(1)

        repo_id = repos[0][0]
        if len(repos) > 1:
            click.echo(
                f"Warning: {len(repos)} repos found; comparing first repo only.",
                err=True,
            )
        engine = ConventionEngine(graph, repo_id)
        diff_output = engine.get_diff(yaml_file)
        click.echo(diff_output)


@cli.command("init")
@click.option(
    "--format",
    "fmt",
    type=click.Choice(["yaml", "json"], case_sensitive=False),
    default="yaml",
    help="Config file format (default: yaml)",
)
def init_config(fmt: str):
    """Create a default config file in the working directory."""
    cwd = Path.cwd()

    # Check for any existing config variant to avoid shadowing
    for name in _CONFIG_NAMES:
        existing = cwd / name
        if existing.exists():
            click.echo(f"Config already exists at {existing}")
            return

    ext = ".yml" if fmt == "yaml" else ".json"
    config_file = cwd / f"sqlprism{ext}"

    default_config = {
        "db_path": str(DEFAULT_DB_PATH),
        "sql_dialect": None,
        "repos": {
            "my-project": {
                "path": str(Path.cwd()),
                "dialect": None,
                "dialect_overrides": {
                    "# athena/": "athena",
                    "# starrocks/": "starrocks",
                },
            },
        },
        "sqlmesh_repos": {
            "# my-sqlmesh-project": {
                "project_path": "/path/to/sqlmesh/folder",
                "env_file": "/path/to/.env",
                "dialect": "athena",
                "variables": {"GRACE_PERIOD": 7},
            },
        },
        "dbt_repos": {
            "# my-dbt-project": {
                "project_path": "/path/to/dbt/project",
                "env_file": "/path/to/.env",
                "target": "dev",
                "dialect": "starrocks",
                "dbt_command": "uv run dbt",
            },
        },
    }

    if fmt == "yaml":
        config_file.write_text(
            yaml.dump(default_config, default_flow_style=False, sort_keys=False)
        )
    else:
        config_file.write_text(json.dumps(default_config, indent=2))
    click.echo(f"Created config at {config_file}")
    click.echo("Edit it to add your repos, then run: sqlprism reindex")


def main():
    cli()


if __name__ == "__main__":
    main()
